project:
  type: book
  output-dir: docs

book:
  title: "Solutions to _Statistical Computing with R (2ed)_ by Maria Rizzo"
  author: "Dan Yavorsky"
  site-url: https://dyavorsky.github.io/rizzo-stat-computing/
  repo-url: https://github.com/dyavorsky/rizzo-stat-computing
  repo-actions: edit
  chapters:
    - index.qmd
    - chapters/01_intro.qmd
    - chapters/02_probstat.qmd
    - chapters/03_genrv.qmd
    - chapters/04_genrp.qmd
    - chapters/05_viz.qmd
    - chapters/06_mcvar.qmd
    - chapters/07_mcinf.qmd
    - chapters/08_bootjack.qmd
    - chapters/09_resamp.qmd
    - chapters/10_permute.qmd
    - chapters/11_mcmc.qmd
    - chapters/12_densityest.qmd
    - chapters/13_numerical.qmd
    - chapters/14_optim.qmd
    - chapters/15_program.qmd

format:
  html:
    toc: true
    number-depth: 1
    theme: 
      light: cosmo
      dark: darkly

execute:
  freeze: auto
  keep-md: false



